# Generated by Django 4.2.2 on 2023-06-08 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_x_ray_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='x_ray',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 16, 23, 8, 963277, tzinfo=datetime.timezone.utc)),
        ),
    ]
